recurring_donation.settings:
  type: config_object
  label: 'Recurring PayPal donations'
  mapping:
    single:
      type: mapping
      label: 'Single donation type'
      mapping:
        label:
          type: label
          label: 'Single donation label'
    recurring:
      type: mapping
      label: 'Recurring donation types'
      mapping:
        label:
          type: label
          label: 'Recurring donation label'
    button:
      type: label
      label: 'Donate button text'
