recurring_donation.settings:
  type: config_object
  label: 'Recurring PayPal donations'
  mapping:
    label:
      type: mapping
      label: 'Donation types'
      mapping:
        single:
          type: label
          label: 'Single donation label'
        recurring:
          type: label
          label: 'Recurring donation label'
    button:
      type: label
      label: 'Donate button text'
